### ISSUE TITLE
Object DOMDocument should be created.

### ISSUE THREAD

**Issue by jarnail104** [digitalDataLayer/magento2#2]
I installed this on multisite and it produce this error on home page of main site:

> Object DOMDocument should be created.

Everything (Admin,other sites) is working fine except main site. 
This is error log:
`a:4:{i:0;s:37:"Object DOMDocument should be created.";i:1;s:12360:"#0 /chroot/home/PATH-TO-SITE/html/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(95): Magento\Framework\View\Element\UiComponent\Config\DomMerger->getDom()
#1 /chroot/home/PATH-TO-SITE/html/vendor/magento/module-ui/Model/Manager.php(258): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
#2 /chroot/home/PATH-TO-SITE/html/vendor/magento/module-ui/Model/Manager.php(166): Magento\Ui\Model\Manager->prepare('persomi_ddl')
#3 /chroot/home/PATH-TO-SITE/html/vendor/magento/framework/View/Element/UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('persomi_ddl')
#4 /chroot/home/PATH-TO-SITE/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('persomi_ddl', NULL, Array)`

Magento version: 2.1.3

**Comment by mvitorino** [comment]
Hi, can you tell me what site you are setting up the extension for?

**Comment by mvitorino** [comment]
I have added some logging in the suspected problem area. Please update to most recent version and let me know what exception is being logged.
